### ISSUE TITLE
Streaming for fastertransformer using GPRC

### ISSUE THREAD

**Issue by rtalaricw** [triton-inference-server/fastertransformer_backend#26]
Hi, Can we stream using GPRC for the fastertransformer?

**Comment by byshiue** [comment]
It should be, but we never test it.

**Comment by salanki** [comment]
Any pointers on _how_ to do it?

**Comment by byshiue** [comment]
Let me use `t5_end_to_end_test.py` as an example. 
1. Make sure you can run this example by http client, make sure the workflow works for you.
2. Replace all `client_util = httpclient` by `client_util = grpcclient`. (There are two points in the t5 example)
3. Change `url = "localhost:8000"` to `url = "localhost:8001"`
4. Remove https://github.com/triton-inference-server/fastertransformer_backend/blob/main/tools/t5_utils/t5_end_to_end_test.py#L93 since it is not supported in grpc client.
5. Run serving.

**Comment by salanki** [comment]
As I read that example, it isn’t streaming the generated tokens, it is running the full completion and then returning the entire set of tokens at once. Am I reading that incorrectly?

**Comment by byshiue** [comment]
FasterTransformer backend does not support streaming now because it encapsulate all generation steps in one forward call.

**Comment by byshiue** [comment]
streaming feature is supported in latest release. Please refer https://github.com/triton-inference-server/fastertransformer_backend/blob/main/docs/gpt_guide.md#decoupled-mode.
